routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('transaksi', TransaksiController::class);

app/Models/Barang.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Barang extends Model
{
    use HasFactory;

    /**
    * fillable
    *
    * @var array
    */
    protected $fillable = [
        'nama_barang', 'harga_satuan'
    ];
}

app/Models/Pembelian.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pembelian extends Model
{
    use HasFactory;
    /**
    * fillable
    *
    * @var array
    */
    protected $fillable = [
        'transaksi_pembelian_id', 'master_barang_id', 'jumlah', 'harga_satuan'
    ];
}

app/Models/Transaksi.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Transaksi extends Model
{
    use HasFactory;
    /**
    * fillable
    *
    * @var array
    */
    protected $fillable = [
        'total_harga'
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/TransaksiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Transaksi;
use App\Models\Barang;
use App\Models\Pembelian;
use Illuminate\Support\Facades\Storage;


class TransaksiController extends Controller
{
    //
    /**
     * index
     *
     * @return void
     */
    public function index()
    {

        $transaksis = Transaksi::select('transaksis.*', 'pembelians.jumlah as jumlah', 'pembelians.transaksi_pembelian_id', 'barangs.nama_barang as nama_barang', 'barangs.harga_satuan as harga_satuan')
        ->join('pembelians', 'transaksis.id', '=', 'pembelians.transaksi_pembelian_id')
        ->join('barangs', 'pembelians.master_barang_id', '=', 'barangs.id')
        ->latest()
        ->paginate(10);
        return view('transaksi', compact('transaksis'));
    }

    public function create()
    {
        $barangs    = Barang::latest()->paginate(10);
        return view('add', compact('barangs'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'barang' => 'required',
            'jumlah' => 'required',
            'total'  => 'required',
        ]);

        $barang = $request->barang;
        $jumlah = $request->jumlah;
        $total  = $request->total;

        $satuan = $total/$jumlah;

        $transaksi  = Transaksi::create([
            'total_harga' => $total
        ]);

        $pembelian  = Pembelian::create([
            'transaksi_pembelian_id' => $transaksi->id,
            'master_barang_id' => $barang,
            'jumlah' => $jumlah,
            'harga_satuan' => $satuan
        ]);

        if($transaksi){
            return redirect()->route('transaksi.index')->with(['success' => 'inserted']);
        }else{
            return redirect()->route('transaksi.index')->with(['error' => 'fail to insert']);
        }
    }

    public function edit($id)
    {
        $transaksis = Transaksi::select('transaksis.*', 'pembelians.jumlah as jumlah', 'pembelians.transaksi_pembelian_id', 'barangs.nama_barang as nama_barang', 'barangs.harga_satuan as harga_satuan')
        ->join('pembelians', 'transaksis.id', '=', 'pembelians.transaksi_pembelian_id')
        ->join('barangs', 'pembelians.master_barang_id', '=', 'barangs.id')
        ->latest()
        ->where('transaksis.id', '=', $id)
        ->paginate(1);
        // echo json_encode($transaksis);
        return view('edit', compact('transaksis'));
        // return view('edit', compact('content'));
    }
}

resources/views/add.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Add Data</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body style="background: lightgray">

    <div class="container mt-5 mb-5">
        <div class="row">
            <div class="col-md-12">
                <div class="card border-0 shadow rounded">
                    <div class="card-body">
                        <form action="{{ route('transaksi.store') }}" method="POST" enctype="multipart/form-data">
                        
                            @csrf

                            <div class="form-group">
                                <label class="font-weight-bold">Barang</label>
                                <select name="barang" required onchange="tampil_total();" id="barang" class="form-control">
                                    @forelse ($barangs as $barang)
                                    <option value="{{$barang->id}}">{{$barang->nama_barang}} - {{$barang->harga_satuan}}</option>
                                    @empty
                                    @endforelse
                                </select>
                                <!-- <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="barang" harga="{{ $barang->harga_barang }}" value="{{ $barang->id }}" id="exampleCheckbox">
                                    <label class="form-check-label" for="exampleCheckbox">
                                        {{ $barang->nama_barang }}
                                    </label>
                                </div> -->


                                <!-- <input type="file" class="form-control @error('image') is-invalid @enderror" name="url"> -->
                            
                                <!-- error message untuk title -->
                                @error('barang')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                            
                            <div class="form-group">
                                <label class="font-weight-bold">Kuantitas</label>
                                <input type="number" required onkeyup="tampil_total();" class="form-control @error('jumlah') is-invalid @enderror" name="jumlah" id="jumlah" value="{{ old('jumlah') }}" placeholder="Kuantitas">
                            
                                <!-- error message untuk title -->
                                @error('title')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label class="font-weight-bold">Total</label>
                                <input type="number" required class="form-control" name="total" id="total" value="0">
                                <!-- <textarea class="form-control @error('content') is-invalid @enderror" name="desc" rows="5" placeholder="Masukkan Konten Blog">{{ old('desc') }}</textarea> -->
                            
                                <!-- error message untuk content -->
                                @error('desc')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>

                            <button type="submit" class="btn btn-md btn-primary">SIMPAN</button>
                            <!-- <button type="reset" class="btn btn-md btn-warning">RESET</button> -->

                        </form> 
                    </div>
                </div>
            </div>
        </div>
    </div>
    
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://cdn.ckeditor.com/4.13.1/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace( 'content' );

    function tampil_total(){
        let kuantitas   = $("#jumlah").val();
        let barang      = $('#barang option:selected').html();
        let hargas      = barang.split(" - ");
        console.log(barang);
        let harga       = hargas[1]; 
        console.log(harga);
        let total       = kuantitas*harga;

        $("#total").val(total);
    }
</script>
</body>
</html>

resources/views/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Edit</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body style="background: lightgray">

    <div class="container mt-5 mb-5">
        <div class="row">
            <div class="col-md-12">
                <div class="card border-0 shadow rounded">
                    <div class="card-body">
                        <form action="" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            @forelse ($transaksis as $transaksi)
                            <div class="form-group">
                                <label class="font-weight-bold">Nama Barang</label>
                                <input type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('nama_barang', $transaksi->nama_barang) }}" readonly>
                            </div>

                            <div class="form-group">
                                <label class="font-weight-bold">Jumlah</label>
                                <input type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('jumlah', $transaksi->jumlah) }}" readonly>
                            </div>

                            <div class="form-group">
                                <label class="font-weight-bold">Satuan</label>
                                <input type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('harga_satuan', $transaksi->harga_satuan) }}" readonly>
                            </div>

                            <div class="form-group">
                                <label class="font-weight-bold">Total</label>
                                <input type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('total_harga', $transaksi->total_harga) }}" readonly>
                            </div>

                            <div class="form-group">
                                <label class="font-weight-bold">Tanggal</label>
                                <input type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('created_at', $transaksi->created_at) }}" readonly>
                            </div>
                            @empty
                            @endforelse

                            
                        </form> 
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://cdn.ckeditor.com/4.13.1/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace( 'content' );
</script>
</body>
</html>

resources/views/transaksi.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Laravel CRUD</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
</head>
<body style="background: lightgray">

    <div class="container mt-5">
        <div class="row">
            <div class="col-md-12">
                <div class="card border-0 shadow rounded">
                    <div class="card-body">
                        <a href="{{ route('transaksi.create') }}" class="btn btn-md btn-success mb-3">Add Transkasi</a>
                        <table class="table table-bordered">
                            <thead>
                              <tr>
                                <th scope="col">Barang</th>
                                <th scope="col">Jumlah</th>
                                <th scope="col">Satuan</th>
                                <th scope="col">Total</th>
                                <th scope="col">Date</th>
                                <th scope="col">#</th>
                              </tr>
                            </thead>
                            <tbody>
                              @forelse ($transaksis as $transaksi)
                                <tr>
                                    
                                    <td>{{ $transaksi->nama_barang }}</td>
                                    <td>{{ $transaksi->jumlah }}</td>
                                    <td>{!! $transaksi->harga_satuan !!}</td>
                                    <td>{!! $transaksi->total_harga !!}</td>
                                    <td>{!! $transaksi->created_at !!}</td>
                                    <td class="text-center">
                                        <a href="{{ route('transaksi.edit', $transaksi->id) }}" class="btn btn-sm btn-primary">View</a>
                                        
                                    </td>
                                </tr>
                              @empty
                                  <div class="alert alert-danger">
                                      Data Transaksi belum Tersedia.
                                  </div>
                              @endforelse
                            </tbody>
                          </table>  
                          {{ $transaksis->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <script>
        //message with toastr
        @if(session()->has('success'))
        
            toastr.success('{{ session('success') }}', 'BERHASIL!'); 

        @elseif(session()->has('error'))

            toastr.error('{{ session('error') }}', 'GAGAL!'); 
            
        @endif
    </script>

</body>
</html>